# TravisCI configuration for username/projectname

_shared_script_check_author: &script_check_author |
  Check_author()
  {
    local author="$1"
    local github_api_url="https://api.github.com/search/users"
    echo "Checking ${author} ..."
    curl -s -G --data-urlencode "q=type:user in:email ${author}" "${github_api_url}" \
      | grep -F -x '  "total_count": 1,'
  }
  test -z "${TRAVIS_COMMIT_RANGE}" \
    || git show --no-patch --pretty="format:%ae" "${TRAVIS_COMMIT_RANGE}" \
    | sort -u \
    | while read -r author; do Check_author "${author}"; done

language: "php"
os:
  - "linux"
dist: "bionic"

stages:
  - "commits"
  - "test"

php:
  #- "8.0snapshot"
  - "7.4"
  - "7.3"

jobs:
  include:
    - stage: "commits"
      name: "Check file execution bits"
      before_install: "skip"
      install: "skip"
      script: |
        # No files should be executable
        test -z "$(find . -type f -not -path "./.git/*" -executable)"
    - name: "Check packages.json"
      language: "node_js"
      node_js: "12"
      cache: "yarn"
      before_install: "skip"
      install: "yarn install"
      script:
        - "yarn lint"
        - "yarn build"
        - "yarn run archive"

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"
  ## Use Composer v1
  #- "composer self-update --1"
  - "composer validate --strict"

install:
  - "composer install"

script:
  - ""
