# TravisCI configuration for 45-North-Ventures-LLC/jackpine

language: "php"
os:
  - "linux"
dist: "bionic"

stages:
  - "commits"
  - "test"

php:
  #- "8.0snapshot"
  - "7.4"
  - "7.3"

jobs:
  include:
    - stage: "commits"
      name: "Check file execution bits"
      before_install: "skip"
      install: "skip"
      script: |
        # No files should be executable
        test -z "$(find . -type f -not -path "./.git/*" -executable)"

    - stage: "test"
      name: "Check assets"
      language: "node_js"
      node_js: "12"
      cache: "yarn"
      before_install: "skip"
      install: "yarn install --non-interactive --frozen-lockfile"
      script:
        - "yarn run lint"
        - "yarn run build"
        - "yarn run archive"

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"
  ## Use Composer v1
  #- "composer self-update --1"
  - "composer validate --strict"

install:
  - "composer install"

script:
  - "echo 'CI needs unit tests or static analysis.'"
